# To test these tools in Fedora and/or Ubuntu:
#
#   $ podman compose run --rm -it <fedora|ubuntu|ubuntu-24.04>
---
x-base: &base
    working_dir: /root/project
    volumes:
      - ./:/root/project:ro
      # Mount kubeconfig so we can access contexts.
      - ${KUBECONFIG:-${HOME}/.kube/config}:/root/.kube/config

services:
  fedora:
    <<: *base
    profiles: [fedora]
    image: docker.io/library/fedora:43

  ubuntu:
    <<: *base
    profiles: [ubuntu]
    image: docker.io/library/ubuntu:25.10

  ubuntu-24.04:
    <<: *base
    profiles: [ubuntu-24.04]
    image: docker.io/library/ubuntu:24.04
